<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 around_the_world_in_80_models_posts.glb
Author: Abby Crawford (https://sketchfab.com/abby)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/around-the-world-in-80-models-posts-39582edb72a94568a5e8a9b69c2c2b24
Title: Around the World in 80 Models Posts
-->

<script>
  import { Group } from 'three'
  import { forwardEventHandlers, T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const { gltf } = useGltf('/src/assets/around_the_world_in_80_models_posts.glb')

  const component = forwardEventHandlers()
</script>

{#if $gltf}
  <T type={ref} {...$$restProps} bind:this={$component}>
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
      <T.Group rotation={[Math.PI / 2, 0, 0]}>
        <T.Mesh
          geometry={$gltf.nodes.Earth_Surfacemat_0.geometry}
          material={$gltf.materials['Surface.mat']}
          scale={100}
        />
      </T.Group>
    </T.Group>

    <slot {ref} />
  </T>
{/if}
