<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ../assets/scene.gltf
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-windy-day-fb78f4cc938144e6902dd5cff354d525
Title: A Windy Day
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/src/assets/scene.gltf')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback"/>
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="sketchfabtimeframe">
          <T.Group name="Object_2" scale={0}>
            <T.Group name="frame_49">
              <T.Points
                      name="Object_4"
                      geometry={gltf.nodes.Object_4.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_5"
                      geometry={gltf.nodes.Object_5.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_6"
                      geometry={gltf.nodes.Object_6.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_7" scale={0}>
            <T.Group name="frame_48">
              <T.Points
                      name="Object_9"
                      geometry={gltf.nodes.Object_9.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_10"
                      geometry={gltf.nodes.Object_10.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_11"
                      geometry={gltf.nodes.Object_11.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_12" scale={0}>
            <T.Group name="frame_47">
              <T.Points
                      name="Object_14"
                      geometry={gltf.nodes.Object_14.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_15"
                      geometry={gltf.nodes.Object_15.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_16"
                      geometry={gltf.nodes.Object_16.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_17" scale={0}>
            <T.Group name="frame_46">
              <T.Points
                      name="Object_19"
                      geometry={gltf.nodes.Object_19.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_20"
                      geometry={gltf.nodes.Object_20.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_21"
                      geometry={gltf.nodes.Object_21.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_22" scale={0}>
            <T.Group name="frame_45">
              <T.Points
                      name="Object_24"
                      geometry={gltf.nodes.Object_24.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_25"
                      geometry={gltf.nodes.Object_25.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_26"
                      geometry={gltf.nodes.Object_26.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_27" scale={0}>
            <T.Group name="frame_44">
              <T.Points
                      name="Object_29"
                      geometry={gltf.nodes.Object_29.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_30"
                      geometry={gltf.nodes.Object_30.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_31"
                      geometry={gltf.nodes.Object_31.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_32" scale={0}>
            <T.Group name="frame_43">
              <T.Points
                      name="Object_34"
                      geometry={gltf.nodes.Object_34.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_35"
                      geometry={gltf.nodes.Object_35.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_36"
                      geometry={gltf.nodes.Object_36.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_37" scale={0}>
            <T.Group name="frame_42">
              <T.Points
                      name="Object_39"
                      geometry={gltf.nodes.Object_39.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_40"
                      geometry={gltf.nodes.Object_40.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_41"
                      geometry={gltf.nodes.Object_41.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_42" scale={0}>
            <T.Group name="frame_41">
              <T.Points
                      name="Object_44"
                      geometry={gltf.nodes.Object_44.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_45"
                      geometry={gltf.nodes.Object_45.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_46"
                      geometry={gltf.nodes.Object_46.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_47" scale={0}>
            <T.Group name="frame_40">
              <T.Points
                      name="Object_49"
                      geometry={gltf.nodes.Object_49.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_50"
                      geometry={gltf.nodes.Object_50.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_51"
                      geometry={gltf.nodes.Object_51.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_52" scale={0}>
            <T.Group name="frame_39">
              <T.Points
                      name="Object_54"
                      geometry={gltf.nodes.Object_54.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_55"
                      geometry={gltf.nodes.Object_55.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_56"
                      geometry={gltf.nodes.Object_56.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_57" scale={0}>
            <T.Group name="frame_38">
              <T.Points
                      name="Object_59"
                      geometry={gltf.nodes.Object_59.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_60"
                      geometry={gltf.nodes.Object_60.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_61"
                      geometry={gltf.nodes.Object_61.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_62" scale={0}>
            <T.Group name="frame_37">
              <T.Points
                      name="Object_64"
                      geometry={gltf.nodes.Object_64.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_65"
                      geometry={gltf.nodes.Object_65.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_66"
                      geometry={gltf.nodes.Object_66.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_67" scale={0}>
            <T.Group name="frame_36">
              <T.Points
                      name="Object_69"
                      geometry={gltf.nodes.Object_69.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_70"
                      geometry={gltf.nodes.Object_70.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_71"
                      geometry={gltf.nodes.Object_71.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_72" scale={0}>
            <T.Group name="frame_35">
              <T.Points
                      name="Object_74"
                      geometry={gltf.nodes.Object_74.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_75"
                      geometry={gltf.nodes.Object_75.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_76"
                      geometry={gltf.nodes.Object_76.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_77" scale={0}>
            <T.Group name="frame_34">
              <T.Points
                      name="Object_79"
                      geometry={gltf.nodes.Object_79.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_80"
                      geometry={gltf.nodes.Object_80.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_81"
                      geometry={gltf.nodes.Object_81.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_82" scale={0}>
            <T.Group name="frame_33">
              <T.Points
                      name="Object_84"
                      geometry={gltf.nodes.Object_84.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_85"
                      geometry={gltf.nodes.Object_85.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_86"
                      geometry={gltf.nodes.Object_86.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_87" scale={0}>
            <T.Group name="frame_32">
              <T.Points
                      name="Object_89"
                      geometry={gltf.nodes.Object_89.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_90"
                      geometry={gltf.nodes.Object_90.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_91"
                      geometry={gltf.nodes.Object_91.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_92" scale={0}>
            <T.Group name="frame_31">
              <T.Points
                      name="Object_94"
                      geometry={gltf.nodes.Object_94.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_95"
                      geometry={gltf.nodes.Object_95.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_96"
                      geometry={gltf.nodes.Object_96.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_97" scale={0}>
            <T.Group name="frame_30">
              <T.Points
                      name="Object_99"
                      geometry={gltf.nodes.Object_99.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_100"
                      geometry={gltf.nodes.Object_100.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_101"
                      geometry={gltf.nodes.Object_101.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_102" scale={0}>
            <T.Group name="frame_29">
              <T.Points
                      name="Object_104"
                      geometry={gltf.nodes.Object_104.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_105"
                      geometry={gltf.nodes.Object_105.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_106"
                      geometry={gltf.nodes.Object_106.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_107" scale={0}>
            <T.Group name="frame_28">
              <T.Points
                      name="Object_109"
                      geometry={gltf.nodes.Object_109.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_110"
                      geometry={gltf.nodes.Object_110.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_111"
                      geometry={gltf.nodes.Object_111.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_112" scale={0}>
            <T.Group name="frame_27">
              <T.Points
                      name="Object_114"
                      geometry={gltf.nodes.Object_114.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_115"
                      geometry={gltf.nodes.Object_115.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_116"
                      geometry={gltf.nodes.Object_116.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_117" scale={0}>
            <T.Group name="frame_26">
              <T.Points
                      name="Object_119"
                      geometry={gltf.nodes.Object_119.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_120"
                      geometry={gltf.nodes.Object_120.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_121"
                      geometry={gltf.nodes.Object_121.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_122" scale={0}>
            <T.Group name="frame_25">
              <T.Points
                      name="Object_124"
                      geometry={gltf.nodes.Object_124.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_125"
                      geometry={gltf.nodes.Object_125.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_126"
                      geometry={gltf.nodes.Object_126.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_127" scale={0}>
            <T.Group name="frame_24">
              <T.Points
                      name="Object_129"
                      geometry={gltf.nodes.Object_129.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_130"
                      geometry={gltf.nodes.Object_130.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_131"
                      geometry={gltf.nodes.Object_131.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_132" scale={0}>
            <T.Group name="frame_23">
              <T.Points
                      name="Object_134"
                      geometry={gltf.nodes.Object_134.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_135"
                      geometry={gltf.nodes.Object_135.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_136"
                      geometry={gltf.nodes.Object_136.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_137" scale={0}>
            <T.Group name="frame_22">
              <T.Points
                      name="Object_139"
                      geometry={gltf.nodes.Object_139.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_140"
                      geometry={gltf.nodes.Object_140.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_141"
                      geometry={gltf.nodes.Object_141.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_142" scale={0}>
            <T.Group name="frame_21">
              <T.Points
                      name="Object_144"
                      geometry={gltf.nodes.Object_144.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_145"
                      geometry={gltf.nodes.Object_145.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_146"
                      geometry={gltf.nodes.Object_146.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_147" scale={0}>
            <T.Group name="frame_20">
              <T.Points
                      name="Object_149"
                      geometry={gltf.nodes.Object_149.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_150"
                      geometry={gltf.nodes.Object_150.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_151"
                      geometry={gltf.nodes.Object_151.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_152" scale={0}>
            <T.Group name="frame_19">
              <T.Points
                      name="Object_154"
                      geometry={gltf.nodes.Object_154.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_155"
                      geometry={gltf.nodes.Object_155.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_156"
                      geometry={gltf.nodes.Object_156.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_157" scale={0}>
            <T.Group name="frame_18">
              <T.Points
                      name="Object_159"
                      geometry={gltf.nodes.Object_159.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_160"
                      geometry={gltf.nodes.Object_160.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_161"
                      geometry={gltf.nodes.Object_161.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_162" scale={0}>
            <T.Group name="frame_17">
              <T.Points
                      name="Object_164"
                      geometry={gltf.nodes.Object_164.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_165"
                      geometry={gltf.nodes.Object_165.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_166"
                      geometry={gltf.nodes.Object_166.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_167" scale={0}>
            <T.Group name="frame_16">
              <T.Points
                      name="Object_169"
                      geometry={gltf.nodes.Object_169.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_170"
                      geometry={gltf.nodes.Object_170.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_171"
                      geometry={gltf.nodes.Object_171.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_172" scale={0}>
            <T.Group name="frame_15">
              <T.Points
                      name="Object_174"
                      geometry={gltf.nodes.Object_174.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_175"
                      geometry={gltf.nodes.Object_175.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_176"
                      geometry={gltf.nodes.Object_176.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_177" scale={0}>
            <T.Group name="frame_14">
              <T.Points
                      name="Object_179"
                      geometry={gltf.nodes.Object_179.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_180"
                      geometry={gltf.nodes.Object_180.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_181"
                      geometry={gltf.nodes.Object_181.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_182" scale={0}>
            <T.Group name="frame_13">
              <T.Points
                      name="Object_184"
                      geometry={gltf.nodes.Object_184.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_185"
                      geometry={gltf.nodes.Object_185.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_186"
                      geometry={gltf.nodes.Object_186.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_187" scale={0}>
            <T.Group name="frame_12">
              <T.Points
                      name="Object_189"
                      geometry={gltf.nodes.Object_189.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_190"
                      geometry={gltf.nodes.Object_190.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_191"
                      geometry={gltf.nodes.Object_191.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_192" scale={0}>
            <T.Group name="frame_11">
              <T.Points
                      name="Object_194"
                      geometry={gltf.nodes.Object_194.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_195"
                      geometry={gltf.nodes.Object_195.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_196"
                      geometry={gltf.nodes.Object_196.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_197" scale={0}>
            <T.Group name="frame_10">
              <T.Points
                      name="Object_199"
                      geometry={gltf.nodes.Object_199.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_200"
                      geometry={gltf.nodes.Object_200.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_201"
                      geometry={gltf.nodes.Object_201.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_202" scale={0}>
            <T.Group name="frame_9">
              <T.Points
                      name="Object_204"
                      geometry={gltf.nodes.Object_204.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_205"
                      geometry={gltf.nodes.Object_205.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_206"
                      geometry={gltf.nodes.Object_206.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_207" scale={0}>
            <T.Group name="frame_8">
              <T.Points
                      name="Object_209"
                      geometry={gltf.nodes.Object_209.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_210"
                      geometry={gltf.nodes.Object_210.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_211"
                      geometry={gltf.nodes.Object_211.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_212" scale={0}>
            <T.Group name="frame_7">
              <T.Points
                      name="Object_214"
                      geometry={gltf.nodes.Object_214.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_215"
                      geometry={gltf.nodes.Object_215.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_216"
                      geometry={gltf.nodes.Object_216.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_217" scale={0}>
            <T.Group name="frame_6">
              <T.Points
                      name="Object_219"
                      geometry={gltf.nodes.Object_219.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_220"
                      geometry={gltf.nodes.Object_220.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_221"
                      geometry={gltf.nodes.Object_221.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_222" scale={0}>
            <T.Group name="frame_5">
              <T.Points
                      name="Object_224"
                      geometry={gltf.nodes.Object_224.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_225"
                      geometry={gltf.nodes.Object_225.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_226"
                      geometry={gltf.nodes.Object_226.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_227" scale={0}>
            <T.Group name="frame_4">
              <T.Points
                      name="Object_229"
                      geometry={gltf.nodes.Object_229.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_230"
                      geometry={gltf.nodes.Object_230.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_231"
                      geometry={gltf.nodes.Object_231.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_232" scale={0}>
            <T.Group name="frame_3">
              <T.Points
                      name="Object_234"
                      geometry={gltf.nodes.Object_234.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_235"
                      geometry={gltf.nodes.Object_235.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_236"
                      geometry={gltf.nodes.Object_236.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_237" scale={0}>
            <T.Group name="frame_2">
              <T.Points
                      name="Object_239"
                      geometry={gltf.nodes.Object_239.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_240"
                      geometry={gltf.nodes.Object_240.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_241"
                      geometry={gltf.nodes.Object_241.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_242" scale={0}>
            <T.Group name="frame_1">
              <T.Points
                      name="Object_244"
                      geometry={gltf.nodes.Object_244.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_245"
                      geometry={gltf.nodes.Object_245.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_246"
                      geometry={gltf.nodes.Object_246.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
          <T.Group name="Object_247">
            <T.Group name="frame_0">
              <T.Points
                      name="Object_249"
                      geometry={gltf.nodes.Object_249.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_250"
                      geometry={gltf.nodes.Object_250.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
              <T.Points
                      name="Object_251"
                      geometry={gltf.nodes.Object_251.geometry}
                      material={gltf.materials['Scene_-_Root']}
              />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error}/>
  {/await}

  <slot {ref}/>
</T>
